# Generated by Django 5.2.5 on 2025-09-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_video_file_episode_video_url'),
        ('user', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='content.story'),
        ),
    ]
