# Generated by Django 5.2.5 on 2025-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
