# Generated by Django 5.2.5 on 2025-09-17 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_episode_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.story'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
