# Generated by Django 5.2.5 on 2025-09-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_episode_audio_file_alter_episode_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='video_file',
            new_name='video_url',
        ),
    ]
