# Generated by Django 5.2.5 on 2025-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_video_file_episode_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
