"""
Django settings for stories project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%-_p8s&o5o9wg1cr$1(exu)i6j_76m+ghp1++@dfgh8^tbrjnd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google", 
    "banners",
    "content",
    "dashboard",
]
SITE_ID = 1
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ]
}
 
AUTH_USER_MODEL = "user.User"
 
 
import os

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
DROPBOX_ACCESS_TOKEN = "sl.u.AF9ON7ZT1Gde0SjcV4eEPcW4PvWhg2r9lqD3DfaUuxZsTDujlvoLItbm4zAEDoX79S0FpRM8EStxySXt2E4R2NA96hKtpGTq77J8AJhGH7g3V71km6qn3U9T6HLT9RS7I8o5TqQJhwKlIEjf1Y1Ic_sjuyjhPauR8kpFqo4GVHdFGeLhKI_taz00UK23u4jUWl9v7cz4L7nPBUHS8huhWu_SlWxCxhvKN-DfxJGLjyXxMDXOzgZQOt2F5zc5OhCqC8CGcV0S0sV4-szLQXthxLa81wVCLH8UNgDX4ztNNfBWKDCibl6MoWbUqw2fkP2Kb3g3EeIVSAv6Fxhv-2tFGpH4DrS0FKoz5A03_3JfH8iIDYE3uWqvJbaZ7DHP3fHDDBkt9FEhSRBHyygsi1XGWSN7kVw-vFW9_OiCJiyAnKhmBtROl4Poj2u8ej2vxY7CMIQ0TktVqJHJE0B9xkzAe2Wf0B88qYU0AKGnKU34D5VO-2Mulc3HZpuj1Sid8NuH1cJy4krYfKZsewtVFqwvvgHfP0BxtRz_JN47oNX8jJ3w5fHoyu1zKQQZqxYdI13iCXpd9Drw6iKxkz7NV_rm2CcfzK2DwD50hwL1IQHIq3HINEaRYAJbtwgw1pvf8oIXJ8TNV9dR5EY7bvJvLaDjH9dTPFgbaFVx-XSDunhvk8OWFrJpvlq9Q1xchLK_WC4LVtDeF5q-Xf6xHz7eHo-Za5ryL9ODzD9VxOxFDeScdiuDki_Z8SVKx06L-UCDpPFTkTVQiMJdaCjUtQDukb2Oc8z-GJwtkR8B9SSJ0EF5IP-_wi0zX4G6HEdFzAZNwWwusDIkQWeCvhn3WGk0qwY2LilyJZ7mZZU_tBttMGY_QJfLa5MqW8Avq8gBsldTU6g-hJpZhOZ_IbTgSniyhyEclQJazkM95JGeQK55kdmErugl6K4BnraUofaTf7PzRDVAlXmZ42avMBdE889N8xltQIXNccwBzHcm7J7oifGW9e9kE_mkD-ZW-bLcADXq8CFXsQE6jl3aHtKMPPv4BBniXiLF2C-7VoX211PO6sAFFbhBJpzM3Qp9-x6DnJk6oUZdwzMrY0hRHnWKA8L-TUbTCQUeyJC1oPLk8bag43fLzDZzd47trJ7ns7r_ZScUDzyQqP9JjLIO2LeCVskuMyUjC9haO7XRUBp4p4rbIiObQZ9G9Wtb1IVb-KEbRGAkpP4WQGR9cr-dYVvfHoFn6PRQqIZmRRyVeFcthHkt0b1Ir2CrycDTVIOJrP2jWhtxOGFEGLqX0KHk7wUPMwdYfZJlSI3ws6mC77oMG5r0NQ67k6tQzwEiu5QkA7jDLWZ8G2x6-uki9cOQbZhm7n0Oz_lIE03l4usKwKPkxBQTv5o2XheUO1_rzyif87uyZG20eWXaxy0AhEdZs-dn2hZQE7xpGOKru80yfgZh1oqKtqxRL3jCAQ"
DROPBOX_BASE_PATH = "/episodes/videos/"

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# تسجيل الدخول باستخدام الإيميل فقط
ACCOUNT_LOGIN_METHODS = {"email"}

# الحقول المطلوبة في التسجيل
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]




# okid ovtb cplu vvwo
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "eng.sara.reiad@gmail.com"
EMAIL_HOST_PASSWORD = "okid ovtb cplu vvwo"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'stories.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stories.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'  

# هنا بيتجمع كل الملفات الثابتة بعد أمر collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
