"""
Django settings for stories project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%-_p8s&o5o9wg1cr$1(exu)i6j_76m+ghp1++@dfgh8^tbrjnd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google", 
    "banners",
    "content",
    "dashboard",
]
SITE_ID = 1
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ]
}
 
AUTH_USER_MODEL = "user.User"
 
 
import os

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
DROPBOX_ACCESS_TOKEN = "sl.u.AF_EEKcL9KZzENqrH21SEZppckKWxMU0061CnNt2vcRoeQIPd2pk0FoxxICLh1FfUMXkomNKcs3WkvW7kz-Q6o7LWmjXbeSrVFrbcEG95Uz97ssrn_blfnWsLKrsBDewmN3LrLnRZ8lgkpViPZnRHPYLCX37M1nqg26EhzzJZeYQDcsVDOibrR-Zxc_Vb6aupwkVIUABPP5Cn6VGOj0AZ4zKy-wZNkohAbhLAuD3BzcOLMsa3-l8VXm2mTYyBNY1q-89p5zcYRHWeKEmYtpeJ3UGfGvBXrrYloGqKnZLUw4j7_8eNFGI-m6zGDyX7PjbL1iX66dShe-bziJicipfzBP6HYTmJSTLpjkBbGX51PRodr21T0vRSK1XStBk4zJoBD9b7iZ_8eQEbYrgs3C7OmCqMWYNU80GLr0PUMp43JRDfddVCud6hO8xYUmk7wXqx7qB8LICzypP6yJ_Tkg7oBj6T43yuWuBU9CVaemBhtBWi054ZnXMtTvVBQ7x0mhFQi09dJullFY5itrFCWmxgKjPa3TO7IGRckziIZiQu924GRszxaoKKzdvZUYpwBwcS1pIBIswmfXwDkhX_Fd1G7BxOfekcW1ScxqqT8iAXrxJsW-CTfzVpv7dhl891-5ec_i2AtQCx4xM6Zr011A1rCn3Rur2QwKHvjTuB-Wnw3rSKa1eCZ3Vyw7vB-pwkM0kfj-ZHlQLn93N1pAztRQAhK79RpQ7EpCkkTWM9KpJA2q5eOpOtID5VjwR6IQ9tRh180-6MZIND1CYspyllnjyP0zvNqk918u4s49MN2zh1S13UbdYO2j64-CBEAK-qJRU-qNmW5C9nbiZpr5fmT-HUv78VP17Ls_0i2Udej8oETHcOqGpuxC6v4FVvA1tC1z8NnrufZqrSNT72b11SGDwhwz7-vKzP0wusUXDxlOvhfeqrUDsbCChE5xHGT3feJy04H0M-s3sxHtv73V0s1Dau-GUkSlEuF4VmLiZMfp5YaPBuDfcFm8gGxGhpK8Lip4dJxH8Xu1lT7vBLaL5R6jgwlzlttgcC2vUsFZ4q2svxjj7q6ZbosjPfNZLE59dZzfWXDt8RWOFmKCvbxTuPW0qXYMy_r7iyG8ZqOmodG-WAI1N_C-XcC3wXIrC9Zy70-3JM0SQgTyQ23IfpLHchtqDW6sNbE-f5D1DfuP5ZejXl-liKMzjRxURE6A2mQxJBqWoC5evU3uPAqGWecjtOpj8Z2QWAEuf1-i_hVtoD1N8opGTmdQqRyamVoHyRy67vRbV164OHxCeNQsxKRBpYS88nTerPFu6P6wEnnicu-k2YtZz7LLvr94fggzQA4HjKjcTPABh0DyrJajEIcpYZZZIL-u63NBsVCTSmEWhVm_CUvEt1n7AH0jViKbKXptxM24BPrUOUZTnyv6xiUg4Il6DwiAwFvSGp88-OrvE6KAT8YW_dg"
DROPBOX_BASE_PATH = "/episodes/videos/"

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# تسجيل الدخول باستخدام الإيميل فقط
ACCOUNT_LOGIN_METHODS = {"email"}

# الحقول المطلوبة في التسجيل
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]




# okid ovtb cplu vvwo
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "eng.sara.reiad@gmail.com"
EMAIL_HOST_PASSWORD = "okid ovtb cplu vvwo"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'stories.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stories.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'  

# هنا بيتجمع كل الملفات الثابتة بعد أمر collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
